import { 
    Box,
    Button,
    Flex,
    Input,
    InputGroup,
    InputLeftElement,
    Text
} from '@chakra-ui/react'
import Head from 'next/head'
import Link from 'next/link'
import { FaEnvelope } from 'react-icons/fa'

export default function EsqueciMinhaSenha() {
    return (
        <Flex 
            bg='gray.900'
            h='100vh'
            color='white'
            align='center'
            justify='center'
        >    

            <Head>
                <title>Esqueci minha senha</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

        <Flex
            justify='center'
            flexDir='column'
            px={4}
        >
            <Box>
                <Text 
                    fontWeight='bold'
                    fontSize='3xl'
                >
                    Esqueci minha senha
                </Text>
                <Text color='whiteAlpha.400'>
                    Informe seus dados para recuperar sua senha
                </Text>
            </Box>

            <InputGroup mt='4'>
                <InputLeftElement
                    pointerEvents='none'
                    // eslint-disable-next-line react/no-children-prop
                    children={<FaEnvelope />}
                />
                <Input 
                    type='password' 
                    placeholder='Email'
                    borderColor='blackAlpha.500'
                    _placeholder={{
                    color: 'gray.400'
                    }}
                    _hover={{
                    color: 'none'
                    }}
                    focusBorderColor='blackAlpha.500'
                    bg='blackAlpha.500'
                />
            </InputGroup>
            <Button 
                colorScheme='messenger'
                mt='8'
            >
                Recuperar senha
            </Button>
            <Text 
                mt='4'
                align='left'
            >
                Voltar para o
                <Text 
                    as='u'
                    _hover={{
                    color: 'gray.400'
                    }}
                    ml='1'
                >
                    <Link href='/'>
                    Login
                    </Link>
                </Text>
            </Text>

        </Flex>


        </Flex>
    )
}
