import Head from 'next/head'
import { 
  Box, 
  Button, 
  Divider, 
  Flex, 
  InputGroup, 
  InputLeftElement, 
  Text, 
  Input,
  Link
} from '@chakra-ui/react'
import { FaGoogle, FaRegEnvelope, FaLock } from 'react-icons/fa'

export default function Home() {
  return (
    <Flex 
      bg='gray.900'
      h='100vh'
      color='white'
      align='center'
      justify='center'
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        justify='center'
        flexDir='column'
      >
        <Box>
          <Text 
            fontWeight='bold'
            fontSize='3xl'
          >
            Bem-vindo de volta
          </Text>
          <Text color='whiteAlpha.400'>
            Bem-vindo de volta, informe suas credênciais para o Login
          </Text>
        </Box>
        <Button 
          /* colorScheme='blackAlpha'  */
          colorScheme='red'
          leftIcon={<FaGoogle />}
          mt='4'
        >
          Login com o Google
        </Button>

        <Flex
          align='center'
          justify='center'
          gap={3}
          mt='4'
        >
          <Divider w={16} />
          <Text>
            Ou
          </Text>
          <Divider w={16} />
        </Flex>

        <InputGroup mt='4'>
          <InputLeftElement
            pointerEvents='none'
            // eslint-disable-next-line react/no-children-prop
            children={<FaRegEnvelope />}
          />
          <Input 
            type='text' 
            placeholder='Usuário'
            borderColor='blackAlpha.500'
            _placeholder={{
              color: 'gray.400'
            }}
            _hover={{
              color: 'none'
            }}
            focusBorderColor='blackAlpha.500'
            bg='blackAlpha.500'
          />
        </InputGroup>

        <InputGroup mt='4'>
          <InputLeftElement
            pointerEvents='none'
            // eslint-disable-next-line react/no-children-prop
            children={<FaLock />}
          />
          <Input 
            type='password' 
            placeholder='Senha'
            borderColor='blackAlpha.500'
            _placeholder={{
              color: 'gray.400'
            }}
            _hover={{
              color: 'none'
            }}
            focusBorderColor='blackAlpha.500'
            bg='blackAlpha.500'
          />
        </InputGroup>

        <Text 
          as='u' 
          mt='4'
          _hover={{
            color: 'gray.400'
          }}
          align='right'
        >
          <Link>
            Esqueci minha senha
          </Link>
        </Text>

        <Button 
          colorScheme='messenger'
          mt='4'
        >
          Login
        </Button>

        <Text 
          mt='4'
          align='center'
        >
          Ainda não possui uma conta? 
          <Text 
            as='u'
            _hover={{
              color: 'gray.400'
            }}
            ml='1'
          >
            <Link>
              Cadastre-se
            </Link>
          </Text>
        </Text>

      </Flex>

    </Flex>
  )
}
